# Build and install rofi
# Build and install rofi
- name: "Checking rofi installation status."
  shell: 'dpkg -s rofi | grep "Status: install ok installed"'
  register: rofi_installed
  ignore_errors: true
  changed_when: false

- name: "Checking rofi installed version."
  shell: dpkg-query --showformat='dpkg --compare-versions "${Version}" "ge" "{{ debuild_rofi.git_branch }}"' -W rofi | sh
  register: rofi_status
  ignore_errors: true
  when: "rofi_installed.rc == 0"
  changed_when: false

- name: 'Building rofi.'
  import_tasks: rofi.yml
  environment:
    GITREV: '{{ debuild_rofi.git_branch }}'
    GIT_URL: '{{ debuild_rofi.git_src }}'
  when: "rofi_installed.rc == 1 or rofi_status.rc != 0"
  changed_when: false
